parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Controller\Api\NewsController:
        tags: [ 'controller.service_arguments' ]
    App\Controller\Api\SourceController:
        tags: [ 'controller.service_arguments' ]
    App\Controller\Api\CategoryController:
        tags: [ 'controller.service_arguments' ]
    App\Storage\NewsStorage:
        arguments:
            $newsService: '@App\Service\NewsService'
            $newsCache: '@App\Storage\NewsCache'